---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lc.
--- DateTime: 2026/9/29 16:48
---
-- Release the session lock only if we still own it.
-- KEYS[1] = lock key
-- ARGV[1] = our token
-- Plain GET + DEL is not atomic: if the key expires between the two calls and
-- another request takes the lock, we would delete *their* lock.
if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
else
    return 0
end
