---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lc.
--- DateTime: 2026/9/29 16:49
---
-- Extend the TTL only if we still own the lock.
-- KEYS[1] = lock key
-- ARGV[1] = our token
-- ARGV[2] = new TTL in milliseconds
if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('pexpire', KEYS[1], ARGV[2])
else
    return 0
end
